export const mockCompanies = [
  {
    id: '1',
    name: 'Vercel',
    website: 'https://vercel.com',
    description: 'The frontend cloud platform for modern web applications',
    industry: 'Infrastructure',
    stage: 'Series D',
    fundingRaised: '$150M',
    headquarters: 'San Francisco, CA',
    foundedYear: 2015,
    employeeCount: '500-1000',
    logo: 'https://assets.vercel.com/image/upload/q_auto/front/favicon/vercel/57x57.png',
  },
  {
    id: '2',
    name: 'Anthropic',
    website: 'https://anthropic.com',
    description: 'AI safety company building helpful, harmless, and honest AI systems',
    industry: 'AI/ML',
    stage: 'Series C',
    fundingRaised: '$5B+',
    headquarters: 'San Francisco, CA',
    foundedYear: 2021,
    employeeCount: '500+',
    logo: 'https://avatars.githubusercontent.com/u/39519015?s=200&v=4',
  },
  {
    id: '3',
    name: 'Stripe',
    website: 'https://stripe.com',
    description: 'Financial infrastructure platform for the internet',
    industry: 'Fintech',
    stage: 'Private',
    fundingRaised: '$2B+',
    headquarters: 'San Francisco, CA',
    foundedYear: 2010,
    employeeCount: '7000+',
    logo: 'https://www.stripe.com/img/v3/press/downloads/logos/logos_solid_1200x630_STP_DefaultBlue.png',
  },
  {
    id: '4',
    name: 'Figure AI',
    website: 'https://www.figure.ai',
    description: 'Robotics company building general-purpose humanoid robots',
    industry: 'Robotics/AI',
    stage: 'Series B',
    fundingRaised: '$675M',
    headquarters: 'Sunnyvale, CA',
    foundedYear: 2022,
    employeeCount: '200-500',
    logo: 'https://pbs.twimg.com/profile_images/1681823188624805888/LfbLQoJu_400x400.jpg',
  },
  {
    id: '5',
    name: 'Canva',
    website: 'https://canva.com',
    description: 'Online design platform making professional design accessible',
    industry: 'Design/Productivity',
    stage: 'Series D',
    fundingRaised: '$600M',
    headquarters: 'Sydney, Australia',
    foundedYear: 2013,
    employeeCount: '1000+',
    logo: 'https://canva.com/favicon.ico',
  },
  {
    id: '6',
    name: 'Scale AI',
    website: 'https://scale.com',
    description: 'Data platform for AI, enabling companies to build and improve AI systems',
    industry: 'Data/AI',
    stage: 'Series D',
    fundingRaised: '$320M',
    headquarters: 'San Francisco, CA',
    foundedYear: 2016,
    employeeCount: '300-500',
    logo: 'https://static.scale.com/web/scale-logo-dark.svg',
  },
  {
    id: '7',
    name: 'Notion',
    website: 'https://notion.so',
    description: 'All-in-one workspace for notes, tasks, databases, and collaboration',
    industry: 'Productivity',
    stage: 'Series C',
    fundingRaised: '$343M',
    headquarters: 'San Francisco, CA',
    foundedYear: 2016,
    employeeCount: '300+',
    logo: 'https://www.notion.so/image/https%3A%2F%2Fassets.notion-static.com%2F59ff41e2-190e-43f9-b636-d982589f9324%2Fnotion-app-icon.png?table=block&id=de73beb0-89f8-4fa1-9255-99c70f1fddeb&cache=v2',
  },
  {
    id: '8',
    name: 'OpenAI',
    website: 'https://openai.com',
    description: 'AI research laboratory building safe, beneficial artificial general intelligence',
    industry: 'AI/ML',
    stage: 'Private',
    fundingRaised: '$13B+',
    headquarters: 'San Francisco, CA',
    foundedYear: 2015,
    employeeCount: '500+',
    logo: 'https://openai.com/favicon.ico',
  },
];
